
all:
  children:
    app:
    db:
  vars:
    ansible_user: 'ubuntu'
    ansible_ssh_private_key_file: ~/.ssh/appuser

app:
  hosts:
    appserver:
      ansible_host: 178.154.225.160

db:
  hosts:
    dbserver:
      ansible_host: 130.193.37.196
